name: Build and Deploy to Client
on: [push]
  

jobs:
  deploy-to-client:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # server IP address
          key: ${{ secrets.SSH_KEY }} # key for server
          username: ${{ secrets.SSH_USERNAME }} # username for server
          # passphrase: ${{ secrets.CLIENT_PASSPHRASE }} # passphrase for client side

          script: |
            cd ~/test/cyber-guardian-frontend
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts # gather SSH public keys from servers
            cd ~/test/cyber-guardian-frontend
            echo 'CD into frontend folder'
            git pull origin
            git reset --hard origin
            #rm -r ~/client/*
            #mv -t ~/client/ ~/test/cyber-guardian-frontend/*
            echo 'Moved to correct folder'
            echo 'Successful deployment to Digital Ocean'
            
