name: 'Dastardly Scan Action'
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  scan-client:
    runs-on: ubuntu-latest
    steps:
      - name: Run Dastardly Action Step
        continue-on-error: true                        # This allows subsequent steps to run even if this step fails
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://cyberguardian.info'
